[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "critica-failure"
authors = [{name = "Samarendra", email = "samarendrapani1998@gmail.com"}]
dynamic = ["version", "description"]
